#!/usr/bin/env bash
# Accepts 2 arguments and displays information about those arguments

#1st argument is the domain, 2nd argument is the subdomain
get_info () {
    FULL_DOM="$2.$1"
    RECORD="$(dig $FULL_DOM | grep -A2 'ANSWER SECTION:' | grep -A1 'IN' | awk '{ print $4 }')"
    DEST="$(dig $FULL_DOM | grep -A2 'ANSWER SECTION:' | grep -A1 'IN' | awk '{ print $5 }')"
    echo "The subdomain $2 is a $RECORD record and points to $DEST"
}

if [ "$#" -eq 1 ]
then
    get_info $1 "www"
    get_info $1 "lb-01"
    get_info $1 "web-01"
    get_info $1 "web-02"
elif [ "$#" -eq 2 ]
then
    get_info $1 $2
fi
