#!/usr/bin/env bash 
#Installs and configure HAproxy on a load balancer server        
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo apt-get update
sudo apt-get -y install haproxy=1.5.\*
echo "ENABLE=1" | sudo tee -a /etc/default/haproxy
echo -e '\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n' | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backendnodes\n\tbalance roundrobin\n\tserver 385-web-01 35.229.84.121:80 check\n\tserver 385-web-02 34.73.176.33:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
