#!/usr/bin/env bash
#Prints out "Holberton School" in a while loop and "Hi" on its 9th iteration
i="0"
while [ $i -ne "10" ]; do
if [ $i -eq "8" ]; then
echo "Hi"
fi
if [ $i -ne "8" ]; then
echo "Holberton School"
fi
((i++))
done
