#!/usr/bin/env bash
#Loops through 1-10 and displays bad luck for the 4th loop and good luck for the 8the loop; displays holberton school for the other loops
i="1"
while [ $i -lt "21" ]; do
echo $i
case $i in
"4")
echo "bad luck from China"
;;
"9")
echo "bad luck from Japan"
;;
"17")
echo "bad luck from Italy"
esac
((i++))
done
