#!/usr/bin/env bash
#Installs and configures a nginx web server on our web-01 server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i '29s/.*/rewrite /redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
