#!/usr/bin/env bash
#Configs an Ubuntu server with certain requirements
cp /etc/hosts ~/hosts.new
sed -i '/localhost/c\127.0.0.2	localhost' ~/hosts.new
sed -i '/facebook.com/c\8.8.8.8\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
