#!/usr/bin/env bash
#Configs an Ubuntu server with certain requirements
cp /etc/hosts ~/hosts.new
sed -i '/127/c\127.0.0.2	localhost' ~/hosts.new
cat ~/hosts.new
FB=$(grep -c "facebook" ~/hosts.new)
if [ "$FB" -eq "0" ]; then
    sed -i '$ a 8.8.8.8	facebook.com' ~/hosts.new
else
    sed -i '/facebook.com/c\8.8.8.8	facebook.com' ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
